# Note: Test set labels are hidden. A 'predictions.json' file is stored after evaluation, which can be
# uploaded to the original DocRED CodaLab challenge.
dataset:
  test_path: ./data/datasets/docred_change/train_removed.json

model:
  # model_path: ./data/models/docred/rel_classify_multi_instance/model.ckpt
  model_path: ./data/runs/2022-08-19/16-19-52/checkpoint/epoch=9-step=30529.ckpt
  tokenizer_path: ./data/models/docred/rel_classify_multi_instance
  encoder_config_path: ./data/models/docred/rel_classify_multi_instance

inference:
  test_batch_size: 1

distribution:
  gpus: []
  accelerator: ''
  prepare_data_per_node: false

hydra:
  run:
    dir: ./data/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: run_config